# Generated by Django 5.2.7 on 2025-10-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('lu', 'Lunch'), ('dn', 'Dinner'), ('all', 'All')], default='all', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('gr', 'Gram'), ('kg', 'Kilogram'), ('pc', 'Piece'), ('l', 'Litre'), ('ml', 'Milliliter')], default='gr', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
