# Generated by Django 5.2.7 on 2025-10-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
