# Generated by Django 5.2.7 on 2025-11-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_en_product_slug_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('lu', 'Lunch'), ('dn', 'Dinner'), ('all', 'All')], db_index=True, default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
