# Generated by Django 5.2.7 on 2025-11-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_slug_remove_product_slug_en_and_more'),
        ('users', '0004_appversion_device_delete_devicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrating',
            name='user',
        ),
        migrations.AddField(
            model_name='productrating',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='users.device'),
            preserve_default=False,
        ),
    ]
