# Generated by Django 5.2.7 on 2025-11-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_cart_product_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='measurement',
            field=models.CharField(choices=[('gr', 'Gram'), ('kg', 'Kilogram'), ('pc', 'Piece'), ('l', 'Litre'), ('ml', 'Milliliter')], default='gr', max_length=16),
        ),
    ]
