# Generated by Django 5.2.7 on 2025-11-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_rename_products_cartproduct_product'),
        ('users', '0004_appversion_device_delete_devicemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='users.device'),
        ),
    ]
