# Generated by Django 5.2.7 on 2025-10-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_birthday_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('laptop', 'Laptop'), ('other', 'Other')], default='other', max_length=10)),
                ('os', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('other', 'Other')], max_length=10, null=True)),
                ('model', models.CharField(blank=True, help_text='Device model name', max_length=100, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
