# Generated by Django 5.2.7 on 2025-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('short_description', models.CharField(max_length=100)),
                ('short_description_en', models.CharField(max_length=100, null=True)),
                ('short_description_uz', models.CharField(max_length=100, null=True)),
                ('long_description', models.TextField()),
                ('long_description_en', models.TextField(null=True)),
                ('long_description_uz', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='histories/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('button_text', models.CharField(default='Подробнее', max_length=50, verbose_name='Tugma matni')),
                ('button_text_en', models.CharField(default='Подробнее', max_length=50, null=True, verbose_name='Tugma matni')),
                ('button_text_uz', models.CharField(default='Подробнее', max_length=50, null=True, verbose_name='Tugma matni')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Tugma havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
