# Generated by Django 5.2.7 on 2025-11-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
        migrations.AlterField(
            model_name='history',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='button_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='button_text_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='button_text_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
