# Generated by Django 5.2.7 on 2025-11-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationsteps',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preparationsteps',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recipescategory',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipescategory',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
