# Generated by Django 5.2.7 on 2025-11-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_avg_rating'),
        ('users', '0004_appversion_device_delete_devicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipesrating',
            name='user',
        ),
        migrations.AddField(
            model_name='recipesrating',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_ratings', to='users.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipesproduct',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
    ]
