# Generated by Django 5.2.7 on 2025-11-03 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipesrating_user_recipesrating_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesrating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
